# Generated by Django 5.2.7 on 2025-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
